spring:
  application:
    name: auth-api
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: auth
    password: auth
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration/auth
    schemas: auth
  data:
    redis:
      host: localhost
      port: 6379
